
import { google } from 'googleapis';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';
import { YoutubeTranscript } from 'youtube-transcript';
import { GoogleGenerativeAI } from '@google/generative-ai';

// Load environment variables
dotenv.config({ path: '.env.local' });

const youtube = google.youtube('v3');
const YOUTUBE_API_KEY = process.env.YOUTUBE_API_KEY;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

const genAI = new GoogleGenerativeAI(GEMINI_API_KEY || '');

export async function analyzeVideo(videoId: string, targetPlatform = 'Short Video/Red/X') {
    console.log(`\n🔍 Analyzing video ID: ${videoId}...`);

    try {
        const videoResponse = await youtube.videos.list({
            key: YOUTUBE_API_KEY,
            part: ['snippet', 'statistics'],
            id: [videoId]
        });

        const video = videoResponse.data.items?.[0];
        if (!video) return null;

        const title = video.snippet?.title || '';
        const description = video.snippet?.description || '';
        const views = parseInt(video.statistics?.viewCount || '0').toLocaleString();
        const url = `https://www.youtube.com/watch?v=${videoId}`;

        let transcript = '';
        try {
            const transcriptItems = await YoutubeTranscript.fetchTranscript(videoId);
            transcript = transcriptItems.map(item => item.text).join(' ').substring(0, 10000);
        } catch (e) {
            console.log(`   (No transcript available for ${videoId}, using description)`);
            transcript = description;
        }

        const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

        const prompt = `
你是一位顶级的 YouTube 爆款内容拆解专家和营销策略师。
我们将研究一个“低粉爆款”视频（粉丝极少但播放量惊人）。

**视频标题:** ${title}
**播放量:** ${views}
**内容片段/转录:** ${transcript}

请根据你的专业知识，给出以下深度的拆解：

1. **爆火原因 (The Why):** 为什么关注人数少且播放量却能达到惊人高度？
2. **内容优势 (Content Edge):** 这个视频相比同类型的视频，赢在哪里？
3. **结构框架 (Framework):** 视频的前10秒、中间和结尾是如何设计的？
4. **受众与需求 (Audience & Needs):** 它的目标受众是谁？满足了什么需求？
5. **核心观点 (Core Insights):** 视频传递的最核心观点是什么？
6. **借镜与参考 (Benchmarks):** 我们可以学习的3个具体战术？

---

### 🚀 创作实验：爆款脚本改写 (Viral Script Draft)

基于以上分析，请为我（作为这台电脑的主人）创作一个适用于 **${targetPlatform}** 的爆款脚本。
- **目标：** 极高完成率和点赞率。
- **结构：** 
    - **钩子 (Hook)**：前3秒，瞬间抓住注意力。
    - **留存内容**：层层递进，解决一个具体痛苦或提供一个意想不到的惊喜。
    - **行动号召 (CTA)**：引导评论和关注。
- **风格：** 简洁、有力、充满激情，去掉废话。如果有复杂的术语，请使用 **Feynman 学习法** 的思路将其简化。

请用中文回答，排版清晰美观。在回答的开头，请包含原视频链接：${url}
`;

        const result = await model.generateContent(prompt);
        return result.response.text();

    } catch (error) {
        console.error(`Error analyzing ${videoId}:`, error);
        return null;
    }
}

export async function run() {
    const topIdsFile = path.join(process.cwd(), 'reports/gems/top-ids.json');
    let videoIds = [];

    if (fs.existsSync(topIdsFile)) {
        videoIds = JSON.parse(fs.readFileSync(topIdsFile, 'utf8'));
        console.log(`✅ Loaded ${videoIds.length} IDs from top-ids.json`);
    } else {
        console.error('❌ top-ids.json not found. Run find-hidden-gems first.');
        process.exit(1);
    }

    const results = [];
    for (const id of videoIds) {
        const analysis = await analyzeVideo(id);
        if (analysis) results.push(analysis);
    }

    const date = new Date().toISOString().split('T')[0];

    // 1. Save as internal report
    const reportPath = path.join(process.cwd(), 'reports/gems/deep-analysis.md');
    fs.writeFileSync(reportPath, `# 🧬 YouTube 低粉爆款深度拆解报告 (${date})\n\n` + results.join('\n\n---\n\n'));

    // 2. Save as Blog Post
    const blogPostPath = path.join(process.cwd(), `posts/${date}-youtube-hidden-gems-analysis.md`);
    const blogContent = `---
title: "🧬 YouTube 低粉爆款深度拆解 (${date})"
author: "Antigravity Analysis Bot"
category: "思维成长"
date: "${date}"
tags: ["YouTube", "爆款拆解", "流量增长", "自动挖掘"]
---

# YouTube 潜力爆款深度分析报告

这是由 **Antigravity Gem Hunter** 自动挖掘并生成的深度内容分析。

` + results.join('\n\n---\n\n') + `

---
*Generated by PotatoAnalytics Hub Automation*
`;

    fs.writeFileSync(blogPostPath, blogContent);
    console.log(`\n✅ Blog post generated: ${blogPostPath}`);
}

if (require.main === module) {
    run();
}
