import { google } from 'googleapis';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';
import { YoutubeTranscript } from 'youtube-transcript';
import { GoogleGenerativeAI } from '@google/generative-ai';

// Load environment variables
dotenv.config({ path: '.env.local' });

const youtube = google.youtube('v3');
const YOUTUBE_API_KEY = process.env.YOUTUBE_API_KEY;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

// Initialize Gemini
const genAI = new GoogleGenerativeAI(GEMINI_API_KEY || '');

const CHANNELS = process.env.YOUTUBE_CHANNELS?.split(',') || [];

async function getChannelId(handle: string) {
    try {
        const response = await youtube.search.list({
            key: YOUTUBE_API_KEY,
            part: ['snippet'],
            q: handle,
            type: ['channel'],
            maxResults: 1
        });
        return response.data.items?.[0]?.id?.channelId;
    } catch (error) {
        console.error(`Error fetching ID for ${handle}:`, error);
        return null;
    }
}

async function summarizeVideo(title: string, transcriptText: string): Promise<string> {
    const model = genAI.getGenerativeModel({ model: "gemini-flash-latest" });

    const prompt = `
  You are an expert learning assistant. Summarize this YouTube video transcript.
  Video Title: "${title}"
  
  Please output in the following Markdown format (in Chinese, simple and profound):
  
  ## 核心观点 (Key Takeaways)
  - [Point 1]
  - [Point 2]
  - [Point 3]
  
  ### 💎 金句 (Golden Quotes)
  > "[Quote 1]"
  > "[Quote 2]"
  
  ### 💡 行动建议 (Actionable Advice)
  - [Advice 1]
  - [Advice 2]
  
  ---
  Transcript:
  ${transcriptText.substring(0, 30000)} // Limit to avoid token limits mostly
  `;

    try {
        const result = await model.generateContent(prompt);
        const response = await result.response;
        return response.text();
    } catch (error) {
        console.error("Gemini Error:", error);
        return "AI Summarization Failed.";
    }
}

async function fetchLatestVideos() {
    if (!YOUTUBE_API_KEY || !GEMINI_API_KEY) {
        console.error('API Keys are missing');
        return;
    }

    console.log(`🔍 Checking ${CHANNELS.length} channels for new content...`);

    // Create learning posts directory
    // content is referenced relative to project root
    const postsDir = path.join(process.cwd(), 'posts/learning');
    if (!fs.existsSync(postsDir)) {
        fs.mkdirSync(postsDir, { recursive: true });
    }

    for (const handle of CHANNELS) {
        const channelId = await getChannelId(handle);
        if (!channelId) continue;

        console.log(`Processing ${handle}...`);

        const response = await youtube.search.list({
            key: YOUTUBE_API_KEY,
            channelId: channelId,
            part: ['snippet'],
            order: 'date',
            maxResults: 1, // Only check the very latest for speed test
            type: ['video']
        });

        const videos = response.data.items || [];
        for (const video of videos) {
            if (!video.id?.videoId) continue;

            const videoId = video.id.videoId;
            const title = video.snippet?.title || 'Unknown Title';
            const date = video.snippet?.publishedAt?.split('T')[0] || '2026-01-01';
            const cleanTitle = title.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase().substring(0, 50);
            const filename = `${date}-${cleanTitle}.md`;
            const filePath = path.join(postsDir, filename);

            if (fs.existsSync(filePath)) {
                console.log(`Skipping already processed: ${title}`);
                continue;
            }

            console.log(`🎥 Found new video: ${title}`);

            try {
                console.log("   Fetching transcript...");
                const transcriptItems = await YoutubeTranscript.fetchTranscript(videoId);
                const transcriptText = transcriptItems.map(item => item.text).join(' ');

                console.log("   Summarizing with Gemini...");
                const summary = await summarizeVideo(title, transcriptText);

                const fileContent = `---
title: "学习笔记: ${title}"
date: "${date}"
tags: ["Learning", "YouTube", "${handle.replace('@', '')}"]
source_url: "https://www.youtube.com/watch?v=${videoId}"
---

# ${title}

${summary}

---
*Auto-generated by PotatoLearning Hub*
`;

                fs.writeFileSync(filePath, fileContent);
                console.log(`✅ Saved: ${filename}`);

            } catch (err) {
                console.error(`   Failed to process ${title}: No transcript or error.`);
            }
        }
    }
}

fetchLatestVideos();
