
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';
import { searchHiddenGems } from './find-hidden-gems';
import { analyzeVideo } from './deep-analyze-gems';

// Load environment variables
dotenv.config({ path: '.env.local' });

const CATEGORIES = [
    "AI科技", "个人成长", "致富商业", "职场效率", "营销案例"
];

async function runDirector() {
    console.log("🎬 New Media Director: Starting daily content loop...\n");

    const date = new Date().toISOString().split('T')[0];
    const results: string[] = [];

    for (const category of CATEGORIES) {
        console.log(`--- Processing Category: ${category} ---`);
        
        // Step 1: Find the absolute top gem for this category
        const gems = await searchHiddenGems(category, 10000, 2000); // Max 10k subs, min 2k views
        
        if (gems.length === 0) {
            console.log(`⚠️ No gems found for ${category}. Skipping.`);
            continue;
        }

        const topGem = gems[0];
        console.log(`🔥 Top Gem Found: "${topGem.title}" (${topGem.viewCount} views, ${topGem.subscriberCount} subs)`);

        // Step 2: Deep Analyze and generate script
        const analysis = await analyzeVideo(topGem.videoId, 'Short Video (Douyin/Red/TikTok)');
        
        if (analysis) {
            results.push(`## 🏷️ Category: ${category}\n\n${analysis}`);
        }
    }

    if (results.length === 0) {
        console.log("❌ No content generated. Check API keys and search parameters.");
        return;
    }

    // Step 3: Save to Blog as a daily draft
    const outputDir = path.join(process.cwd(), 'posts/new-media-drafts');
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

    const filename = `${date}-new-media-auto-draft.md`;
    const filePath = path.join(outputDir, filename);

    const fileContent = `---
title: "🚀 新媒体爆款自动挖掘与脚本创作 (${date})"
author: "Antigravity New Media Director"
category: "New Media"
date: "${date}"
tags: ["自动脚本", "爆款拆解", "流量增长", "智能创作"]
---

# 今日新媒体创作选题与脚本推荐

这是由 **New Media Director** 自动生成的创作闭环。
我们从全网挖掘了低粉爆款，拆解了其流量核心，并为你直接生成了可用的创作脚本。

---

${results.join('\n\n---\n\n')}

---
*Generated by Antigravity New Media Automation*
`;

    fs.writeFileSync(filePath, fileContent);
    console.log(`\n✅ Daily New Media Draft saved: ${filePath}`);
}

runDirector().catch(console.error);
